POST http://localhost:3000/paper/new HTTP/1.1
content-type: application/json

{
  "title": "Title1",
  "source": "Source1",
  "authors": "Authors1 , authors 2, authors3",
  "year": 2019,
  "state": "P",
  "state_expert_opinion": "G"
}

###

GET http://localhost:3000/paper/all HTTP/1.1

###

GET http://localhost:3000/paper/id/1 HTTP/1.1

###

PUT http://localhost:3000/paper/update HTTP/1.1
content-type: application/json

{
  "id": 1,
  "title": "Title1U",
  "source": "Source1U",
  "authors": "Authors1U , authors 2U, authors3U",
  "year": 2019,
  "state": "U",
  "state_expert_opinion": "U",
  "expert_opinion": "photo",
  "link":"link"
}

###


POST http://localhost:3000/article/new HTTP/1.1
content-type: application/json

{
  "name": "Orlova",
  "compilation": "test@test.ru",
  "year": 2019,
  "authors": [
    {
      "name": "Orlova",
      "description": "test@test.ru"
    },
    {
      "id": 1
    }
  ]
}

###


POST http://localhost:3000/article/newAuthors HTTP/1.1
content-type: application/json

{
  "name": "Orlova",
  "description": "test@test.ru"
}

###

GET http://localhost:3000/article/aaa HTTP/1.1

###

POST http://library.vstu.ru/publ_2/publ_result.php HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 112
Content-Type: application/x-www-form-urlencoded
Cookie: _ga=GA1.2.1517549486.1552371516; _ym_uid=1566922000771054986; _ym_d=1566922000; __utma=10425522.1517549486.1552371516.1574772425.1574772425.1; __utmz=10425522.1574772425.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _gid=GA1.2.991526188.1580990735; _ym_isad=1
Host: library.vstu.ru
Origin: http://library.vstu.ru
Referer: http://library.vstu.ru/publ_2/index.php?command=search2
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36

universitet=2&fio=&year_rel=&year_rel1=&year_rel2=&year_reg=&year_reg1=&year_reg2=&faculty=4&kafedra=43&v_publ=0

###

POST /publ_2/publ_result.php HTTP/1.1
Host: library.vstu.ru
Connection: keep-alive
Content-Length: 112
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Origin: http://library.vstu.ru
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://library.vstu.ru/publ_2/index.php?command=search2
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: _ga=GA1.2.1517549486.1552371516; _ym_uid=1566922000771054986; _ym_d=1566922000; __utma=10425522.1517549486.1552371516.1574772425.1574772425.1; __utmz=10425522.1574772425.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _gid=GA1.2.991526188.1580990735; _ym_isad=1

universitet=2&fio=&year_rel=&year_rel1=&year_rel2=&year_reg=&year_reg1=&year_reg2=&faculty=4&kafedra=43&v_publ=0

###

POST http://library.vstu.ru/publ_2/publ_result.php HTTP/1.1
Host: library.vstu.ru
Connection: keep-alive
Content-Length: 116
Cache-Control: max-age=0
Origin: http://library.vstu.ru
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://library.vstu.ru/publ_2/index.php?command=search2
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: _ga=GA1.2.1517549486.1552371516; _ym_uid=1566922000771054986; _ym_d=1566922000; __utma=10425522.1517549486.1552371516.1574772425.1574772425.1; __utmz=10425522.1574772425.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _gid=GA1.2.991526188.1580990735; _ym_isad=1

universitet=2&fio=&year_rel=2020&year_rel1=&year_rel2=&year_reg=&year_reg1=&year_reg2=&faculty=4&kafedra=43&v_publ=0

###

###

POST http://library.vstu.ru/publ_2/index.php?command=search2 HTTP/1.1

###

POST /publ_2/publ_result.php HTTP/1.1
Host: library.vstu.ru
Host: library.vstu.ru
Connection: keep-alive
Content-Length: 116
Cache-Control: max-age=0
Origin: http://library.vstu.ru
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://library.vstu.ru/publ_2/index.php?command=search2
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cookie: _ga=GA1.2.1517549486.1552371516; _ym_uid=1566922000771054986; _ym_d=1566922000; __utma=10425522.1517549486.1552371516.1574772425.1574772425.1; __utmz=10425522.1574772425.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _gid=GA1.2.991526188.1580990735; _ym_isad=1

universitet=2&fio=&year_rel=2020&year_rel1=&year_rel2=&year_reg=&year_reg1=&year_reg2=&faculty=4&kafedra=43&v_publ=0

###

GET http://localhost:3000/paper/res HTTP/1.1

###
